name: Nightly Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker/build-push-action@v1
      env:
        INPUT_REPOSITORY: ${GITHUB_REPOSITORY}/php-nightly
      with:
        username: ${GITHUB_ACTOR}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        dockerfile: .github/Dockerfile.debian
        tags: latest
        tag_with_sha: true
