name: php-nightly

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker/build-push-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: "${{ github.repository }}/php-nightly"
        dockerfile: .github/Dockerfile.debian
        tags: latest
        tag_with_sha: true
